import os
import re

base_dir = '/Volumes/WorkLife/work/alsaalim/alsaalimperfume.shop'

# 1. Fix broken https:./ urls caused by previous replace
def fix_bad_urls(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        rel_dir = os.path.relpath(base_dir, os.path.dirname(filepath))
        root_prefix = '.' if rel_dir == '.' else rel_dir

        # Fix specific cases where "https:./" or similar issues remain
        new_content = content.replace('https:./', './')
        new_content = new_content.replace('https:../', '../')
        new_content = re.sub(r'https://alsaalimperfume\.shop', f'{root_prefix}', new_content)

        # fix the weird "..../" urls that were generated by accident
        new_content = new_content.replace('..../', '../')

        if new_content != content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
            print(f'Fixed bad urls in {os.path.relpath(filepath, base_dir)}')
    except Exception as e:
        print(f"Failed to process bad urls {filepath}: {e}")

# 2. Rename files with query strings and fix references
def fix_query_strings():
    rename_map = {}

    for root, dirs, files in os.walk(base_dir):
        for filename in files:
            if '?' in filename or '%' in filename:
                # Generate new name
                new_name = filename.replace('?', '_').replace('=', '_').replace('&', '_').replace('%', '_')

                # HTML reference
                html_ref = filename
                if filename.endswith('.css') and '.css?' in filename:
                    html_ref = filename[:-4]
                if filename.endswith('.js') and '.js?' in filename:
                    html_ref = filename[:-3]

                rename_map[html_ref] = new_name

                old_path = os.path.join(root, filename)
                new_path = os.path.join(root, new_name)
                os.rename(old_path, new_path)

    print(f"Renamed {len(rename_map)} files with query strings.")

    # Add variants for HTML encoded characters
    extended_map = {}
    for k, v in rename_map.items():
        extended_map[k] = v
        if '&' in k:
            extended_map[k.replace('&', '&amp;')] = v

    for root, dirs, files in os.walk(base_dir):
        for filename in files:
            if filename.endswith(('.html', '.css', '.js', '.json')):
                filepath = os.path.join(root, filename)
                try:
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()

                    new_content = content
                    for html_ref in sorted(extended_map.keys(), key=len, reverse=True):
                        new_ref = extended_map[html_ref]
                        new_content = new_content.replace(html_ref, new_ref)
                        new_content = new_content.replace(html_ref.replace('?', '%3F').replace('=', '%3D').replace('&', '%26'), new_ref)
                        new_content = new_content.replace(html_ref.replace('?', '%3F').replace('=', '%3D').replace('&', '&amp;'), new_ref)

                    def replacer(match):
                        # Extract the query part
                        ext = match.group(1)
                        query = match.group(2)
                        # Replace bad chars with underscores
                        query = query.replace('%3F', '_').replace('?', '_').replace('&amp;', '_').replace('&', '_').replace('%3D', '_').replace('=', '_').replace('%26', '_')
                        return ext + query

                    new_content = re.sub(r'(\.(?:png|jpg|jpeg|gif|svg|webp|js|css))((?:%3F|\?).*?(?:["\'\s>]))', replacer, new_content)

                    if new_content != content:
                        with open(filepath, 'w', encoding='utf-8') as f:
                            f.write(new_content)
                except Exception as e:
                    pass

for root, dirs, files in os.walk(base_dir):
    for filename in files:
        if filename.endswith(('.html', '.css', '.js', '.json')):
            fix_bad_urls(os.path.join(root, filename))

fix_query_strings()
print("Done fixing everything!")
